Misc Changes 2
ZencashOfficial/zexe pull request #104
Opened 2021-06-01 09:46 UTC by DanieleDiBenedetto

- Return indices of all failing proofs from batch verification, accumulate and accumulate verify, rather than just one

2021-06-04 06:38 UTC, phoinic approved these changes
Seems everything ok. As I understand the main goal of changes here is to get all failed proofs at once, not only the single index

2021-06-22 14:12 UTC, albertog78 requested changes

2021-06-22 14:12 UTC, albertog78 commented on algebra/src/fft/evaluations.rs
> +        CanonicalSerialize::serialize_uncompressed(&self.evals, writer)
unneeded. use default implementation

2021-07-01 10:27 UTC, albertog78 approved these changes

2021-10-06 13:07 UTC, merged