Audit fixes 005
ZencashOfficial/zexe pull request #118
Opened 2021-07-19 16:07 UTC by phoinic

2021-07-26 11:12 UTC, DanieleDiBenedetto requested changes

2021-07-26 11:12 UTC, DanieleDiBenedetto commented on primitives/src/merkle_tree/field_based_mht/optimized/mod.rs
>          if processing_step <= 0 || processing_step > last_level_size {
We can remove the check <= 0 since 'processing_step' is an usize, and replace it with  processing_step == 0

2021-07-26 11:12 UTC, DanieleDiBenedetto commented on primitives/src/merkle_tree/field_based_mht/path.rs
> +                Err(format!("FieldBasedMHTPath to FieldBasedBinaryMHTPath convert failed"))?
"There must be only 1 node for each element in the path to be able to perform conversion to a binary path"

2021-07-26 11:12 UTC, DanieleDiBenedetto commented on primitives/src/merkle_tree/field_based_mht/path.rs
> +                Err(format!("FieldBasedMHTPath to FieldBasedBinaryMHTPath convert failed"))?
"Position must be only 0 or 1 for each element in the path to be able to perform conversion to a binary path"

2021-07-26 11:12 UTC, DanieleDiBenedetto commented on r1cs/gadgets/crypto/src/commitment/pedersen/mod.rs
> +                "Number of generators: {} not enough for the selected window size: {}",
"...for the selected num_windows..."

2021-07-26 11:12 UTC, DanieleDiBenedetto commented on r1cs/gadgets/crypto/src/crh/bowe_hopwood/mod.rs
> +                Err(SynthesisError::Other("generators length verification failed".to_owned()))?
"Number of generators: {} not enough for the selected window size: {}",
parameters.generators.len(),
W::NUM_WINDOWS

2021-08-06 08:32 UTC, DanieleDiBenedetto requested changes

2021-08-06 08:32 UTC, DanieleDiBenedetto commented on primitives/src/crh/bowe_hopwood/mod.rs
> +                    W::NUM_WINDOWS
Sorry, this should be W::WINDOW_SIZE

2021-08-06 08:32 UTC, DanieleDiBenedetto commented on proof-systems/src/gm17/verifier.rs
> +    ).unwrap();
Why we are unwrapping here ? We have already the Result as a return type so let's just put "?"

2021-08-06 08:32 UTC, DanieleDiBenedetto commented on proof-systems/src/gm17/verifier.rs
> +    ).unwrap();
Same as above

2021-08-06 08:32 UTC, DanieleDiBenedetto commented on r1cs/gadgets/crypto/src/crh/bowe_hopwood/mod.rs
> +                    W::NUM_WINDOWS
Sorry, here is W::WINDOW_SIZE

2021-08-30 09:54 UTC, DanieleDiBenedetto approved these changes

2021-08-30 09:56 UTC, DanieleDiBenedetto requested changes
Still a couple of old comments to be addressed

2021-08-31 15:10 UTC, phoinic commented
I've rechecked comments, seems everything is done. Also I have reviewed the ginger-lib in general and I have deleted rest of TODOs, and wrapped ".expect" like described in sc-cryptolib

2021-08-31 15:11 UTC, DanieleDiBenedetto commented on algebra/src/fields/models/quadratic_extension.rs
> +                if two_inv.is_none() || alphagit.is_none() {
typo ?

2021-08-31 15:12 UTC, DanieleDiBenedetto approved these changes

2021-08-31 15:12 UTC, DanieleDiBenedetto commented on algebra/src/fields/models/quadratic_extension.rs
> +                if two_inv.is_none() || alphagit.is_none() {
typo -> "alphagit"

2021-10-06 13:10 UTC, merged