Refactor constraint system
ZencashOfficial/zexe pull request #131
Opened 2021-10-14 15:54 UTC by lgiussan

2021-10-18 17:25 UTC, 95DDB requested changes

2021-10-18 17:25 UTC, 95DDB commented on proof-systems/src/gm17/prover.rs
> +// type CoeffVec<T> = SmallVec<[T; 2]>;
Is it needed ? Can we remove it ?

2021-10-18 17:25 UTC, 95DDB commented on r1cs/core/src/constraint_system.rs
> +    fn print_named_objects(&self);
Is this function useful enough to be put in the trait ?

2021-10-18 17:25 UTC, 95DDB commented on r1cs/core/src/constraint_system.rs
> +    fn is_satisfied(&self) -> bool {
No need to override as you've already the same code in the default implementation of this function in the trait

2021-10-18 17:25 UTC, 95DDB commented on r1cs/core/src/constraint_system.rs
> +    fn get(&mut self, path: &str) -> F;
The advantage of having debugging utilities in the trait and having it implemented for our concrete ConstraintSystem is that we don't have to use the TestConstraintSystem and duplicate the code of the circuit to debug/test a given circuit.
However, as of now, our concrete ConstraintSystem, for debugging's sake, is carrying info about names and paths wasting a lot of memory even when we are not interested in debugging, not considering that constraints are evaluated twice when proving, one time by the debugging system and the other time by the prover; while maybe we can solve this last issue by modifying the logic of each prover, we cannot accept the high memory usage to save paths and constraint names. So I see a couple of high-level solutions here, both involves removing the debugging utilities from the ConstraintSystem struct thus saving memory that is wasted when we are not interested in debugging:

- We re-introduce the TestConstraintSystem and simply make it implementing the ConstraintSystemAbstract trait. Of course we need to carry some kind of info so that this implementation is used only in tests and not when performing setup of (pk,vk) and creation of proofs. Then we introduce a very generic function under r1cs/core/lib.rs like:

`fn debug_circuit<ConstraintF: Field, C: ConstraintSynthesizer<ConstraintF>>(circuit:  C) -> (bool, Option<String>) `

Taking a concrete instantiation of ConstraintSynthesizer and returning (true, None) if the circuit instantiation would satisfy a R1CS constraint system, otherwise (false, Some(failed_constraint));

- We implement a Decorator-like pattern to give the ConstraintSystem struct debugging capabilities (e.g. having a Option<TestConstraintSystem> attribute, that is set only in Debug mode (we add a new mode flag to the ConstraintSystem)). The function debug_circuit explained above would be useful also in this situation.

For UTs we can continue using, like before, the TestConstraintSystem/ConstraintSystem + Decorator, while when creating concrete circuits, we can debug by simply commenting in our main function the setup and prove functions and calling the debug_circuit function instead (we would've needed to manually add code inside the generate_constraints function anyway if we don't adopt this solution (at least a call to is_satisfied() and which_is_unsatisfied()))

2021-10-22 08:19 UTC, 95DDB requested changes

2021-10-22 08:19 UTC, 95DDB commented on r1cs/core/src/constraint_system.rs
> -        if self.is_in_setup_mode() {
For elegance, let us allow to call this function only in debug mode

2021-10-22 08:19 UTC, 95DDB commented on r1cs/core/src/constraint_system.rs
> -        if self.is_in_setup_mode() {
For elegance, let us allow to call this function only in debug mode

2021-10-22 08:19 UTC, 95DDB commented on r1cs/core/src/lib.rs
> +    match unsatisfied_constraint {
Can be aggregated into a single expression match cs.which_is_unsatisfied()

2021-10-22 08:19 UTC, 95DDB commented on r1cs/core/src/lib.rs
> +    }
Instead of having two tests, let's use also the set and get utilities to modify the circuit from statisfiabile to unsatisfiable

2021-10-22 08:19 UTC, 95DDB commented on r1cs/core/src/constraint_system.rs
>      /// Returns an Option containing the name of the first constraint which is not satisfied
The functions below are available only if the CS is in Debug mode so it's a bit ugly to put them in the ConstraintSystem trait. Maybe let's do another small step of abstraction and define an additional trait:

`pub trait ConstraintSystemDebugger: ConstraintSystem`

Containing the debugging-related functions, and let the ConstraintSystem struct implementing this trait (no need to change anything, just moving the functions) in a different impl block.
In the UTs nothing will change, the only change will be in the interface of the structs implementing ConstraintSynthesizer where, if desidered, the user can specify CS to be `CS: ConstraintSystem + ConstraintSystemDebugger`

2021-10-22 08:19 UTC, 95DDB commented on r1cs/core/src/constraint_system.rs
> +    /// == true`.
Would be even cleaner to wrap these 3 fields in a new, single, struct, and make it Optional.
You can define a couple of functions inside this struct that updates all three data structures in one go, rather than copy-pasting the same code in alloc, alloc_input and enforce functions

2021-10-25 09:36 UTC, lgiussan commented on r1cs/core/src/lib.rs
> +    }
With the current API, `set` and `get` are methods associated to a constraint system object. However in the tests, only circuits are created, not explicit constraint systems, making therefore impossible to call the set and get utilities. Or maybe I am missing something...

2021-10-25 12:38 UTC, 95DDB commented on r1cs/core/src/lib.rs
> +    }
You're right, sry

2021-10-25 15:02 UTC, 95DDB requested changes

2021-10-25 15:02 UTC, 95DDB commented on r1cs/core/src/constraint_system.rs
> +    pub(crate) fn push_namespace<A, AR>(&mut self, name: A)
Why these functions are pub(crate) ? Can't they be private ?

2021-10-25 15:02 UTC, 95DDB commented on r1cs/core/src/constraint_system.rs
> +            self.debug_info.as_mut().unwrap().add_named_object(NamedObject::Var(var.clone()), annotation);
Maybe, just for elegance, let's wrap the call to `self.debug_info().as_mut().unwrap()` into an additional function `get_debug_info(&self) -> &mut DebugInfo`

2021-10-25 15:02 UTC, 95DDB commented on r1cs/core/src/constraint_system.rs
>      pub fn set_mode(&mut self, mode: SynthesisMode) {
Is this function really useful ? In practical usage doesn't seem so, better to pass directly the mode as a parameter of the new function (tipically, you do new() and then set_mode() anyway)

2021-10-25 15:02 UTC, 95DDB commented on r1cs/core/src/constraint_system.rs
> +                    }
Let's define a constructor for DebugInfo struct (even a simple function called new()) and wrap this code there

2021-10-26 08:06 UTC, 95DDB approved these changes

2022-02-03 14:29 UTC, albertog78 approved these changes

2022-02-04 11:01 UTC, merged