Comments group and pairing gadgets for MNT4/6
ZencashOfficial/zexe pull request #62
Opened 2020-05-19 21:00 UTC by UlrichHaboeck75

Comments on group and pairing gadgets and their MNT4/6 implementation.
The issue #60 (a missing constraint in the MNT6 G2PreparedGadget) is still noted here and need to be erased when merging.

2020-06-04 07:19 UTC, mauriziobinello approved these changes

2020-06-10 10:11 UTC, 95DDB requested changes

2020-06-10 10:11 UTC, DanieleDiBenedetto commented on r1cs/gadgets/std/src/groups/curves/short_weierstrass/mnt/mnt4/mod.rs
> +    Maybe better to move all the preperatory gadgets to pairing-related code
Let's keep this last line for us

2020-06-10 10:11 UTC, DanieleDiBenedetto commented on r1cs/gadgets/std/src/groups/curves/short_weierstrass/mnt/mnt6/mod.rs
> +          CAUTION
You should remove this comment and merge with the last development (so that your fix will be here too) before approving the PR

2020-06-10 10:11 UTC, DanieleDiBenedetto commented on r1cs/gadgets/std/src/groups/mod.rs
> +    // what is this good for? does not use any pre-computations, just ordinary
I wanted to add a slightly different interface, therefore I needed all these stuff. In general, let's keep this comments about improvements and re-styling personal, they don't apply to the purpose of this PR.

2020-06-10 10:11 UTC, DanieleDiBenedetto commented on r1cs/gadgets/std/src/groups/mod.rs
> +    // why no default implementation for 3 bit lookup tables?
See comment above

2020-06-10 10:11 UTC, DanieleDiBenedetto commented on r1cs/gadgets/std/src/groups/mod.rs
> +    Why here? This type of exponentiation is specific to the Pedersen CRH/Commitment scheme.
See comment above

2020-06-10 10:11 UTC, DanieleDiBenedetto commented on r1cs/gadgets/std/src/pairing/mnt4/mod.rs
> +To do: generic treatment of the sign of the trace  using  ATE_IS_LOOP_COUNT_NEG as well as
We already did it and merge into development. Merge the last development branch into this one before approving the PR and remove this comment.

2020-06-10 10:11 UTC, DanieleDiBenedetto commented on r1cs/gadgets/std/src/pairing/mnt4/mod.rs
> +            CAUTION, if clause missing!
See comment above

2020-06-10 10:11 UTC, DanieleDiBenedetto commented on r1cs/gadgets/std/src/pairing/mnt4/mod.rs
> +        as in the pairing primitive, depending on P::FINAL_EXPONENT_LAST_CHUNK_W0_IS_NEG we have to
See comment above

2020-06-10 10:11 UTC, DanieleDiBenedetto commented on r1cs/gadgets/std/src/pairing/mnt6/mod.rs
> +To do: generic treatment of the sign of the trace  using  ATE_IS_LOOP_COUNT_NEG as well as
See comment above

2020-06-10 10:11 UTC, DanieleDiBenedetto commented on r1cs/gadgets/std/src/pairing/mnt6/mod.rs
> +            CAUTION, unitary inverse is missing!
See comment above

2020-06-10 10:11 UTC, DanieleDiBenedetto commented on r1cs/gadgets/std/src/pairing/mnt6/mod.rs
> +        as in the pairing primitive, depending on P::FINAL_EXPONENT_LAST_CHUNK_W0_IS_NEG we have to
See comment above

2021-10-27 09:10 UTC, merged