Read checked unchecked
ZencashOfficial/zexe pull request #67
Opened 2020-06-16 08:33 UTC by DanieleDiBenedetto

2021-02-11 15:23 UTC, albertog78 requested changes

2021-02-11 15:23 UTC, albertog78 commented on r1cs/gadgets/std/src/groups/curves/short_weierstrass/short_weierstrass_jacobian.rs
> +    pub fn add_unsafe<CS: ConstraintSystem<ConstraintF>>(
create a private function to avoid code dup between add and add_unsafe

2021-03-19 10:40 UTC, UlrichHaboeck75 commented on primitives/src/crh/bowe_hopwood/mod.rs
> +    pub fn check_consistency(&self) -> bool {
Why introducing this sanity check? If the setup is cannot be trusted (for example, by having produced the base points via hashing), there is no way to assure security: the linear relation between the base points might be any non-trivial, not detected by this function.

2021-03-19 10:41 UTC, UlrichHaboeck75 commented on primitives/src/crh/pedersen/mod.rs
> +    pub fn check_consistency(&self) -> bool {
As for the Bowe-Hopwood variant: this function does not guarantee security.

2021-03-19 13:18 UTC, UlrichHaboeck75 commented on proof-systems/src/groth16/mod.rs
> +    fn check_gamma_abc_g1_points(gamma_abc_g1: &[E::G1Affine]) -> IoResult<()> {
As for the Pedersen primitive: I do not see any use for this "sanity" check, as it does not guarantee security.

2021-03-19 14:45 UTC, UlrichHaboeck75 commented on proof-systems/src/groth16/mod.rs
> +        // NOTE: a, b_g1 and b_g2 also contains polynomials that evaluate to zero, therefore the
It is extremely unlikely that one of the QAP polynomials evaluates to zero at the toxic waste point tau.
If so, I expect that such would be a danger to security due to the many factorization algorithms for polynomials over finite fields. Therefore it'd make sense to include non-zero checks, too.

2021-03-19 14:48 UTC, UlrichHaboeck75 commented on proof-systems/src/groth16/mod.rs
> +        // TODO: Exclude the points above from the generation procedure
I double-checked all the elements in the vk and the Parameters. None of the elements are redundant, I don't know what the "TODO" addresses.

2021-03-19 14:53 UTC, UlrichHaboeck75 commented on proof-systems/src/groth16/verifier.rs
> +    // which allows us to do a single final exponentiation.
Misleading notation chosen here.
I'd propose to write pairings and use the vk names "e(A,B) = e(alpha_g1, beta_g2) * e(inputs,gamma_g2) ....".

2021-03-19 14:57 UTC, UlrichHaboeck75 commented on r1cs/gadgets/crypto/src/nizk/groth16/mod.rs
> +                P::GTGadget::alloc_without_check(cs.ns(|| "alpha_g1_beta_g2"), || Ok(alpha_g1_beta_g2))?;
It'd worth to add a comment here, that in typical applications verification keys are provided through circuit inputs, hence no allocation checks needed.

2021-03-19 15:06 UTC, UlrichHaboeck75 commented on r1cs/gadgets/crypto/src/nizk/groth16/mod.rs
> +    fn alloc_checked<FN, T, CS: ConstraintSystem<ConstraintF>>(
As for `alloc()`: I cant think of any application where a verification key is a private circuit witness.

2021-03-19 15:23 UTC, UlrichHaboeck75 approved these changes

2021-03-22 11:06 UTC, albertog78 approved these changes

2021-03-22 11:13 UTC, merged